language: dart
dart:
  - stable
script: pub get
jobs:
  include:
    - stage: test
      name: "run tests"
      script: pub run test
      deploy:
        - provider: script
          script: tool/deploy.sh
          on:
            tags: true
    - name: "coverage"
      before_script: gem install coveralls-lcov
      script: pub run test_coverage
      after_success: coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info