language: dart
dart:
  - stable
install:
  - gem install coveralls-lcov
jobs:
  include:
    - stage: compile
      name: "get dependencies"
      script: pub get
    - stage: test
      name: "run tests"
      script: pub run test
    - name: "coverage"
      script: pub run test_coverage
after_success:
  - coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info
deploy:
  - provider: script
    script: tool/deploy.sh
    on:
      tags: true
      branch: master