language: dart
dart:
  - stable
script: pub get
stages:
  - test
  - name: deploy
    if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$
jobs:
  include:
    - stage: test
      name: "tests"
      script: pub run test
    - name: "coverage"
      before_script: gem install coveralls-lcov
      script: pub run test_coverage
      after_success: coveralls-lcov --repo-token $COVERALLS_TOKEN coverage/lcov.info
    - name: "formatting"
      script: dartfmt -n --set-exit-if-changed .
    - name: "static analysis"
      script: dartanalyzer .
    - stage: deploy
      name: "deploy to pub"
      before_script: chmod +x tool/deploy.sh
      script: tool/deploy.sh