name: best_effort_parser
description: Parse unstructured user input of names and dates, with customizable behavior and output types.
version: 1.1.0
homepage: https://github.com/jack-r-warren/best_effort_parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  # test_coverage: ^0.2.0
